### ISSUE TITLE
Calendar / ViewRenderEvent throws an exception when parsing LocalDateTime without time information

### ISSUE THREAD

**Issue by ymlaine** [sebfz1/wicket-jquery-ui#248]
When using the ViewRenderEvent, this exception is thrown. The date is parsed as LocalDateTime instead of LocalDate... For the month view at least. I can write the fix, but I wonder what should be the expected behavior, should the startDate and endDate come with the time information from the web page, or should the type be changed to LocalDate ..?

`org.threeten.bp.format.DateTimeParseException: Text '2016-10-30' could not be parsed at index 10
     at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1587)
     at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
     at org.threeten.bp.LocalDateTime.parse(LocalDateTime.java:444)
     at org.threeten.bp.LocalDateTime.parse(LocalDateTime.java:429)
     at com.googlecode.wicket.jquery.ui.calendar.CalendarBehavior$ViewRenderEvent.<init>(CalendarBehavior.java:819)
     at com.googlecode.wicket.jquery.ui.calendar.CalendarBehavior$OnViewRenderAjaxBehavior.newEvent(CalendarBehavior.java:643)
     at com.googlecode.wicket.jquery.core.ajax.JQueryAjaxBehavior.respond(JQueryAjaxBehavior.java:173)
     at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:593)
     at java.lang.reflect.Method.invoke(Method.java:497)
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:241)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:248)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
`

**Comment by sebfz1** [comment]
Hi Yves-Marie,

Well, sounds weird that I did not realized that, but it indeed seems to be the date only:
https://fullcalendar.io/docs/utilities/Moment/#ambiguously-timed

The view's date/time is given by the `view` parameter of the `viewRender`
https://fullcalendar.io/docs/display/viewRender/
https://fullcalendar.io/docs/views/View_Object/

If you would like to correct this (and test over all views) and submit a PR, it will be my pleasure! :)

Thanks for reporting!
Sebastien.
