### ISSUE TITLE
KendoUI DateTimePicker : NullPointerException when date is empty

### ISSUE THREAD

**Issue by tahitiangabriel** [sebfz1/wicket-jquery-ui#274]
In my form I've added a required DatTimePicker field.

```Java
add(new DateTimePicker("dateDebutRdv", getLocale()).setRequired(true));
```
I use "CompoundPropertyModel" for the model.

When I submit the form without a date I've got the folowwing exception instead of an error feedback : 

```
java.lang.NullPointerException: date must not be null
     at org.threeten.bp.jdk8.Jdk8Methods.requireNonNull(Jdk8Methods.java:79)
     at org.threeten.bp.LocalDateTime.of(LocalDateTime.java:334)
     at com.googlecode.wicket.jquery.core.utils.DateUtils.toDate(DateUtils.java:214)
     at com.googlecode.wicket.jquery.core.utils.DateUtils.dateOf(DateUtils.java:202)
     at com.googlecode.wicket.kendo.ui.form.datetime.DateTimePicker.convertInput(DateTimePicker.java:159)
     at org.apache.wicket.markup.html.form.FormComponent.validate(FormComponent.java:1130)
     at org.apache.wicket.markup.html.form.Form$18.validate(Form.java:1948)
     at org.apache.wicket.markup.html.form.Form$ValidationVisitor.component(Form.java:177)
     at org.apache.wicket.markup.html.form.Form$ValidationVisitor.component(Form.java:161)
     at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:274)
     at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
     at org.apache.wicket.util.visit.Visits.visitPostOrder(Visits.java:245)
     at org.apache.wicket.markup.html.form.FormComponent.visitFormComponentsPostOrder(FormComponent.java:382)
     at org.apache.wicket.markup.html.form.Form.visitFormComponentsPostOrder(Form.java:1154)
     at org.apache.wicket.markup.html.form.Form.validateComponents(Form.java:1940)
     at org.apache.wicket.markup.html.form.Form.validate(Form.java:1882)
     at org.apache.wicket.markup.html.form.Form.process(Form.java:945)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:797)
     at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:708)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at org.apache.wicket.RequestListenerInterface.internalInvoke(RequestListenerInterface.java:258)
     at org.apache.wicket.RequestListenerInterface.invoke(RequestListenerInterface.java:216)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.invokeListener(ListenerInterfaceRequestHandler.java:241)
     at org.apache.wicket.core.request.handler.ListenerInterfaceRequestHandler.respond(ListenerInterfaceRequestHandler.java:234)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
     at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:868)
     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:745)
```

The same thing happen on the demo website : 
http://www.7thweb.net/wicket-jquery-ui/kendo/datetimepicker/KendoDateTimePickerPage

It's working fine on DatePicker and TimePicker.
I'm using version 7.7.0.

You should not call "DateUtils.dateOf" if date and/or time is null I suppose :
```Java
	@Override
	public void convertInput()
	{
		Date date = this.datePicker.getConvertedInput();
		Date time = this.timePicker.getConvertedInput();

		this.setConvertedInput(DateUtils.dateOf(date, time));
	}
```
Also if the DateTimePicker is required you should set the inner datePicker and timePicker as required too.

**Comment by sebfz1** [comment]
good catch, thanks!

**Comment by sebfz1** [comment]
Hi,

Still working on this...

This is actually a more serious issue than I though. I reworked the [Ajax]DateTimePicker and it should be perfect now (unless I missed something! :p)
I still have to update the LocalDateTime counterpart but its causing me some pain right now... I will try do complete this, align with wicket7.x (master) branch and deploy asap. 

Best regards,
Sebastien.

**Comment by sebfz1** [comment]
Hi Gabriel,

`7.7.1-SNAPSHOT` is being deployed...

Would it be possible for you to give it a try before the end of the week ? I will probably do the releases this week-end...

Thanks in advance,
Sebastien.

```
<repositories>
	<repository>
		<id>sonatype-snapshots</id>
		<name>Sonatype Snapshots Repository</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories> 
```

**Comment by tahitiangabriel** [comment]
Sure, I will try it today.
Thank you for the fix.

**Comment by tahitiangabriel** [comment]
It's working fine now. Thank you very much.

**Comment by sebfz1** [comment]
You're very welcome! Thanks for testing!
I will release `7.8.0` over the week-end...
